# .streamlit/secrets.toml

[azure_openai]
AZURE_OPENAI_API_KEY = "a1988b89eb0345029b26945f997e44c4"
AZURE_OPENAI_ENDPOINT = "https://mylessonservice.openai.azure.com/"
AZURE_OPENAI_DEPLOYMENT_NAME = "gpt-35-turbo-16k"
AZURE_OPENAI_API_VERSION = "2023-03-15-preview"
